# Build
FROM golang:1.26-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGOPENABLED=0 GOOS=linux go build -o auth ./cmd/api

# RUN
FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/auth .
EXPOSE 80
CMD ["./auth"]